### ISSUE TITLE
Missing directory

### ISSUE THREAD

**Issue by atom-data** [nawendt/gribr#18]
Hello, I have been trying to download package (gribr) and I keep getting this message 

"C:/rtools40/mingw64/bin/"gcc  -I"C:/Users/x1/d1~1/R/R-40~1.3/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c grib_api_version.c -o grib_api_version.o
In file included from grib_api_version.c:4:
gribr.h:1:10: fatal error: eccodes.h: No such file or directory

leading to a failure in the download. What could be the issue?

**Comment by nawendt** [comment]
Based on the error output, it looks like you are trying to build the package on Windows. Even using Rtools, there is unfortunately not a way to properly build the eccodes library for use with R and gribr. You can still use the package within a Windows environment, but it would have to be through Cygwin or WSL. Once I, or someone else, figures out how to build eccodes with mingw/Rtools, then running on WIndows will be much easier.

**Comment by atom-data** [comment]
Thanks for your prompt response
