### ISSUE TITLE
Devtools Install Instruction in README.md

### ISSUE THREAD

**Issue by JosephAgriNerds** [nawendt/gribr#25]
Currently, the devtools install instructions are as follows:

`devtools::install_github("nawendt/gribr", args = "--configure-args='ECCODES_LIBS=-L/path/to/eccodes/lib ECCODES_CPPFLAGS=-I/path/to/eccodes/include'")`

For me, this causes a problematic argument error. The following worked on my machine, and seems to be the correct syntax for configure args in devtools:

`devtools::install_github("nawendt/gribr", configure.args="ECCODES_LIBS=-L/path/to/eccodes/lib ECCODES_CPPFLAGS=-I/path/to/eccodes/include")`

I would also recommend including `INSTALL_opts = "--install-tests"` so users can check the install against the included tests.

R version 4.3.1, devtools version 2.4.5

**Comment by nawendt** [comment]
It looks like a change was made in what devtools expects at some point. I'll have to update this. Thanks.
